#  **<h1 style='color:Indigo' align="center" > libraries </h1>**

In [52]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline 
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.utils import resample

In [53]:
ourdata= pd.read_csv('D:\\dr_ds.csv') 
ourdata.shape 
#1500   dr_ds5000row..

(319795, 18)

In [54]:
ourdata

,HeartDisease,BMI,Smoking,AlcoholDrinking,Stroke,PhysicalHealth,MentalHealth,DiffWalking,Sex,AgeCategory,Race,Diabetic,PhysicalActivity,GenHealth,SleepTime,Asthma,KidneyDisease,SkinCancer
0,No,16.60,Yes,No,No,3.0,30.0,No,Female,55-59,White,Yes,Yes,Very good,5.0,Yes,No,Yes
1,No,20.34,No,No,Yes,0.0,0.0,No,Female,80 or older,White,No,Yes,Very good,7.0,No,No,No
2,No,26.58,Yes,No,No,20.0,30.0,No,Male,65-69,White,Yes,Yes,Fair,8.0,Yes,No,No
3,No,24.21,No,No,No,0.0,0.0,No,Female,75-79,White,No,No,Good,6.0,No,No,Yes
4,No,23.71,No,No,No,28.0,0.0,Yes,Female,40-44,White,No,Yes,Very good,8.0,No,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
319790,Yes,27.41,Yes,No,No,7.0,0.0,Yes,Male,60-64,Hispanic,Yes,No,Fair,6.0,Yes,No,No
319791,No,29.84,Yes,No,No,0.0,0.0,No,Male,35-39,Hispanic,No,Yes,Very good,5.0,Yes,No,No
319792,No,24.24,No,No,No,0.0,0.0,No,Female,45-49,Hispanic,No,Yes,Good,6.0,No,No,No
319793,No,32.81,No,No,No,0.0,0.0,No,Female,25-29,Hispanic,No,No,Good,12.0,No,No,No
319794,No,46.56,No,No,No,0.0,0.0,No,Female,80 or older,Hispanic,No,Yes,Good,8.0,No,No,No

#  **<h1 style='color:Indigo' align="center" > Data Cleaning </h1>**

In [55]:
duplicates=ourdata.duplicated()
print(sum(duplicates))

18078

In [56]:
ourdata.isna().sum()

HeartDisease        0
BMI                 0
Smoking             0
AlcoholDrinking     0
Stroke              0
PhysicalHealth      0
MentalHealth        0
DiffWalking         0
Sex                 0
AgeCategory         0
Race                0
Diabetic            0
PhysicalActivity    0
GenHealth           0
SleepTime           0
Asthma              0
KidneyDisease       0
SkinCancer          0
dtype: int64

In [57]:
data = ourdata[~ourdata.isin(['?'])] 
data.loc[:100]

,HeartDisease,BMI,Smoking,AlcoholDrinking,Stroke,PhysicalHealth,MentalHealth,DiffWalking,Sex,AgeCategory,Race,Diabetic,PhysicalActivity,GenHealth,SleepTime,Asthma,KidneyDisease,SkinCancer
0,No,16.60,Yes,No,No,3.0,30.0,No,Female,55-59,White,Yes,Yes,Very good,5.0,Yes,No,Yes
1,No,20.34,No,No,Yes,0.0,0.0,No,Female,80 or older,White,No,Yes,Very good,7.0,No,No,No
2,No,26.58,Yes,No,No,20.0,30.0,No,Male,65-69,White,Yes,Yes,Fair,8.0,Yes,No,No
3,No,24.21,No,No,No,0.0,0.0,No,Female,75-79,White,No,No,Good,6.0,No,No,Yes
4,No,23.71,No,No,No,28.0,0.0,Yes,Female,40-44,White,No,Yes,Very good,8.0,No,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96,No,24.02,No,No,No,0.0,14.0,No,Female,70-74,White,No,Yes,Very good,7.0,No,No,Yes
97,No,28.35,Yes,No,No,20.0,0.0,No,Female,65-69,White,No,No,Very good,8.0,No,No,No
98,No,24.37,No,No,No,0.0,0.0,No,Female,55-59,White,No,Yes,Very good,7.0,Yes,No,No
99,No,19.47,Yes,No,No,0.0,10.0,No,Female,65-69,White,No,Yes,Very good,8.0,No,No,No
100,No,24.80,No,No,No,8.0,0.0,No,Female,80 or older,White,"No, borderline diabetes",Yes,Excellent,8.0,No,No,No

#  **<h1 style='color:Indigo' align="center" > Data Processing </h1>**

In [58]:
cols_yes__no_values = ['HeartDisease', 'Smoking', 'AlcoholDrinking', 'Stroke', 'DiffWalking', 'PhysicalActivity',
                       'Asthma', 'KidneyDisease', 'SkinCancer']
yes__no_values = {'No':0, 'Yes':1}
for i in range(0, len(cols_yes__no_values)):
    ourdata[cols_yes__no_values[i]] = ourdata[cols_yes__no_values[i]].replace(yes__no_values)
sex = {'Female':0, 'Male':1}
ourdata['Sex'] = ourdata['Sex'].replace(sex)

ageCategory= {'18-24':0, '25-29':1, '30-34':2, '35-39':3, '40-44':4, '45-49':5, '50-54':6, '55-59':7, '60-64':8,
             '65-69':9, '70-74':10, '75-79':11, '80 or older':12}
ourdata['AgeCategory'] = ourdata['AgeCategory'].replace(ageCategory)
genHealth = {'Poor':0, 'Fair':1, 'Good':2, 'Very good':3, 'Excellent':4}
ourdata['GenHealth'] = ourdata['GenHealth'].replace(genHealth)
diabetic = {'No':0, 'No, borderline diabetes':1, 'Yes (during pregnancy)':2, 'Yes':3}
ourdata['Diabetic'] = ourdata['Diabetic'].replace(diabetic)
ourdata.drop(columns=['Race'], inplace=True)
ourdata

,HeartDisease,BMI,Smoking,AlcoholDrinking,Stroke,PhysicalHealth,MentalHealth,DiffWalking,Sex,AgeCategory,Diabetic,PhysicalActivity,GenHealth,SleepTime,Asthma,KidneyDisease,SkinCancer
0,0,16.60,1,0,0,3.0,30.0,0,0,7,3,1,3,5.0,1,0,1
1,0,20.34,0,0,1,0.0,0.0,0,0,12,0,1,3,7.0,0,0,0
2,0,26.58,1,0,0,20.0,30.0,0,1,9,3,1,1,8.0,1,0,0
3,0,24.21,0,0,0,0.0,0.0,0,0,11,0,0,2,6.0,0,0,1
4,0,23.71,0,0,0,28.0,0.0,1,0,4,0,1,3,8.0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
319790,1,27.41,1,0,0,7.0,0.0,1,1,8,3,0,1,6.0,1,0,0
319791,0,29.84,1,0,0,0.0,0.0,0,1,3,0,1,3,5.0,1,0,0
319792,0,24.24,0,0,0,0.0,0.0,0,0,5,0,1,2,6.0,0,0,0
319793,0,32.81,0,0,0,0.0,0.0,0,0,1,0,0,2,12.0,0,0,0
319794,0,46.56,0,0,0,0.0,0.0,0,0,12,0,1,2,8.0,0,0,0

In [59]:
ourdata_majority_0 = ourdata[(ourdata['HeartDisease']==0)] 
ourdata_minority_1 = ourdata[(ourdata['HeartDisease']==1)] 

ourdata_minority_upsampled = resample(ourdata_minority_1, 
                                 replace=True,    
                                 n_samples= 292225, #292225
                                 random_state=42) 

ourdata_upsampled = pd.concat([ourdata_minority_upsampled, ourdata_majority_0])

In [60]:
ourdata_upsampled

,HeartDisease,BMI,Smoking,AlcoholDrinking,Stroke,PhysicalHealth,MentalHealth,DiffWalking,Sex,AgeCategory,Diabetic,PhysicalActivity,GenHealth,SleepTime,Asthma,KidneyDisease,SkinCancer
276535,1,35.43,0,1,1,0.0,0.0,1,0,12,0,0,2,12.0,0,0,0
183941,1,23.06,0,0,0,0.0,0.0,0,1,12,3,1,1,8.0,0,0,0
8829,1,23.49,1,0,0,5.0,0.0,0,1,12,3,1,1,7.0,0,0,0
60254,1,26.63,1,0,0,4.0,3.0,1,0,12,3,1,1,10.0,0,0,0
251583,1,28.07,0,1,0,0.0,0.0,0,1,11,0,1,4,8.0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
319789,0,22.22,0,0,0,0.0,0.0,0,0,0,0,1,4,8.0,0,0,0
319791,0,29.84,1,0,0,0.0,0.0,0,1,3,0,1,3,5.0,1,0,0
319792,0,24.24,0,0,0,0.0,0.0,0,0,5,0,1,2,6.0,0,0,0
319793,0,32.81,0,0,0,0.0,0.0,0,0,1,0,0,2,12.0,0,0,0
319794,0,46.56,0,0,0,0.0,0.0,0,0,12,0,1,2,8.0,0,0,0

#  **<h1 style='color:Indigo' align="center" > Data Spliting </h1>**

In [61]:
X = ourdata_upsampled.drop(columns='HeartDisease')
y = ourdata_upsampled['HeartDisease']

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 15)

#  **<h1 style='color:Indigo' align="center" > Data Scaling </h1>**

In [62]:

from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)
X_train = pd.DataFrame(X_train)
X_test = pd.DataFrame(X_test)

In [63]:
X_train.shape

(467717, 16)

In [64]:
X_test

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,0.138196,0.0,0.0,0.0,0.000000,0.000000,0.0,1.0,0.000000,0.000000,1.0,1.00,0.347826,0.0,0.0,0.0
1,0.178519,0.0,0.0,0.0,0.000000,0.033333,0.0,0.0,1.000000,0.000000,0.0,0.75,0.304348,1.0,0.0,0.0
2,0.164712,0.0,0.0,0.0,0.066667,0.400000,1.0,0.0,0.833333,1.000000,1.0,0.25,0.217391,0.0,1.0,1.0
3,0.148094,1.0,0.0,0.0,0.100000,1.000000,1.0,0.0,0.666667,0.333333,0.0,0.25,0.304348,0.0,0.0,0.0
4,0.153837,1.0,0.0,0.0,1.000000,0.033333,1.0,0.0,1.000000,0.000000,0.0,0.00,0.217391,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
116925,0.193915,0.0,0.0,0.0,0.000000,0.000000,0.0,1.0,0.333333,0.000000,1.0,1.00,0.304348,0.0,0.0,1.0
116926,0.168622,0.0,0.0,0.0,0.000000,0.500000,0.0,0.0,0.000000,0.000000,1.0,0.75,0.173913,0.0,0.0,0.0
116927,0.150415,0.0,0.0,0.0,0.000000,0.000000,0.0,1.0,0.250000,0.000000,0.0,0.50,0.260870,0.0,0.0,0.0
116928,0.154814,0.0,0.0,0.0,0.000000,0.166667,0.0,0.0,0.500000,0.000000,1.0,0.75,0.260870,0.0,0.0,0.0
116929,0.186217,0.0,0.0,0.0,0.000000,0.166667,0.0,0.0,0.083333,0.000000,1.0,0.75,0.304348,0.0,0.0,0.0

#  **<h1 style='color:Indigo' align="center" > Machine learning Models </h1>**

In [24]:
X = ourdata_upsampled.drop(columns='HeartDisease')
y = ourdata_upsampled['HeartDisease']

In [25]:
ourdata_upsampled

,HeartDisease,BMI,Smoking,AlcoholDrinking,Stroke,PhysicalHealth,MentalHealth,DiffWalking,Sex,AgeCategory,Diabetic,PhysicalActivity,GenHealth,SleepTime,Asthma,KidneyDisease,SkinCancer
276535,1,35.43,0,1,1,0.0,0.0,1,0,12,0,0,2,12.0,0,0,0
183941,1,23.06,0,0,0,0.0,0.0,0,1,12,3,1,1,8.0,0,0,0
8829,1,23.49,1,0,0,5.0,0.0,0,1,12,3,1,1,7.0,0,0,0
60254,1,26.63,1,0,0,4.0,3.0,1,0,12,3,1,1,10.0,0,0,0
251583,1,28.07,0,1,0,0.0,0.0,0,1,11,0,1,4,8.0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
319789,0,22.22,0,0,0,0.0,0.0,0,0,0,0,1,4,8.0,0,0,0
319791,0,29.84,1,0,0,0.0,0.0,0,1,3,0,1,3,5.0,1,0,0
319792,0,24.24,0,0,0,0.0,0.0,0,0,5,0,1,2,6.0,0,0,0
319793,0,32.81,0,0,0,0.0,0.0,0,0,1,0,0,2,12.0,0,0,0
319794,0,46.56,0,0,0,0.0,0.0,0,0,12,0,1,2,8.0,0,0,0

In [26]:
import pandas as pd
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler


pca = PCA()
pca.fit(X)

# calculate the percentage of variance explained by each component
variance = pca.explained_variance_ratio_
variance_ratio = pd.DataFrame(variance, columns=['Explained Variance'])
variance_ratio['Cumulative Variance'] = variance_ratio['Explained Variance'].cumsum()
print(variance_ratio)

components = pd.DataFrame(pca.components_, columns=X.columns)
important_features = components.iloc[0]

    Explained Variance  Cumulative Variance
0             0.508081             0.508081
1             0.243568             0.751649
2             0.176399             0.928048
3             0.046753             0.974800
4             0.010653             0.985453
5             0.006050             0.991503
6             0.003282             0.994784
7             0.001181             0.995965
8             0.000946             0.996912
9             0.000759             0.997670
10            0.000548             0.998219
11            0.000488             0.998706
12            0.000457             0.999163
13            0.000334             0.999498
14            0.000279             0.999777
15            0.000223             1.000000

In [27]:
X.shape

(584647, 16)

In [28]:
from sklearn.decomposition import PCA
import numpy as np
pca = PCA(n_components=8)
pca.fit(X)
X_reduced = pca.transform(X)
print("Original data:\n", X)
print("Reduced data:\n", X_reduced)

Original data:
           BMI  Smoking  AlcoholDrinking  Stroke  PhysicalHealth  MentalHealth  \
276535  35.43        0                1       1             0.0           0.0
183941  23.06        0                0       0             0.0           0.0
8829    23.49        1                0       0             5.0           0.0
60254   26.63        1                0       0             4.0           3.0
251583  28.07        0                1       0             0.0           0.0
...       ...      ...              ...     ...             ...           ...
319789  22.22        0                0       0             0.0           0.0
319791  29.84        1                0       0             0.0           0.0
319792  24.24        0                0       0             0.0           0.0
319793  32.81        0                0       0             0.0           0.0
319794  46.56        0                0       0             0.0           0.0

        DiffWalking  Sex  AgeCategory  Diabetic  PhysicalActivity  GenHealth  \
276535            1    0           12         0                 0          2
183941            0    1           12         3                 1          1
8829              0    1           12         3                 1          1
60254             1    0           12         3                 1          1
251583            0    1           11         0                 1          4
...             ...  ...          ...       ...               ...        ...
319789            0    0            0         0                 1          4
319791            0    1            3         0                 1          3
319792            0    0            5         0                 1          2
319793            0    0            1         0                 0          2
319794            0    0           12         0                 1          2

        SleepTime  Asthma  KidneyDisease  SkinCancer
276535       12.0       0              0           0
183941        8.0       0              0           0
8829          7.0       0              0           0
60254        10.0       0              0           0
251583        8.0       0              0           1
...           ...     ...            ...         ...
319789        8.0       0              0           0
319791        5.0       1              0           0
319792        6.0       0              0           0
319793       12.0       0              0           0
319794        8.0       0              0           0

[584647 rows x 16 columns]
Reduced data:
 [[-5.98933484e+00 -1.72036644e+00  7.12407060e+00 ...  9.78744035e-01
  -6.90980886e-01 -8.13808667e-01]
 [-7.25837183e+00 -1.14282364e+00 -4.97175680e+00 ... -2.57978700e+00
  -5.03703924e-01 -1.20938241e-02]
 [-2.97966085e+00 -3.72770123e+00 -5.15201177e+00 ... -2.39563300e+00
  -3.23128694e-01  6.01992218e-01]
 ...
 [-7.28576530e+00 -2.11781672e-01 -3.69967832e+00 ... -7.47367435e-02
  -8.17115940e-01 -6.95856000e-01]
 [-6.43169078e+00 -2.19244293e-01  4.87845322e+00 ... -2.74145416e-01
  -1.17795520e+00 -7.25104076e-01]
 [-4.67970611e+00 -2.15831676e+00  1.81683919e+01 ...  1.76653556e+00
  -2.21504232e-01 -6.85494355e-01]]

In [29]:
X_reduced.shape

(584647, 8)

In [30]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X_reduced, y, test_size = 0.2, random_state = 15)

In [31]:
X_train.shape

(467717, 8)

In [32]:
X_test.shape

(116930, 8)

In [33]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

X_train = scaler.fit_transform(X_train)

X_test = scaler.transform(X_test)
X_train = pd.DataFrame(X_train)
X_test = pd.DataFrame(X_test)

In [34]:
X_train

,0,1,2,3,4,5,6,7
0,0.028081,0.420952,0.206052,0.791675,0.314884,0.460184,0.408712,0.214848
1,0.305561,0.860466,0.288654,0.219773,0.314125,0.635972,0.522125,0.535059
2,0.042698,0.411606,0.286521,0.733863,0.316152,0.546939,0.541012,0.506881
3,0.851331,0.609582,0.215253,0.277631,0.286807,0.717897,0.596468,0.522170
4,0.043893,0.401840,0.264759,0.521289,0.181061,0.488178,0.199778,0.777041
...,...,...,...,...,...,...,...,...
467712,0.028476,0.423516,0.209108,0.845120,0.317203,0.446395,0.396757,0.180860
467713,0.677635,0.331057,0.105413,0.254290,0.264876,0.596239,0.308774,0.424716
467714,0.182830,0.681925,0.175182,0.275163,0.220074,0.200748,0.506434,0.189701
467715,0.030215,0.388712,0.203019,0.184801,0.365371,0.286598,0.721398,0.539131
467716,0.012912,0.407043,0.118553,0.379735,0.253743,0.558455,0.582966,0.212466

In [35]:
X_test

,0,1,2,3,4,5,6,7
0,0.022991,0.425267,0.188693,0.847093,0.358148,0.468453,0.520504,0.586814
1,0.045233,0.407301,0.223402,0.196444,0.288211,0.606261,0.475160,0.120985
2,0.193253,0.596067,0.206631,0.236802,0.215683,0.190672,0.384034,0.143107
3,0.390837,0.929780,0.183590,0.253734,0.313807,0.393285,0.298547,0.408601
4,0.542571,0.064209,0.156067,0.328775,0.217125,0.602856,0.276516,0.361694
...,...,...,...,...,...,...,...,...
116925,0.034498,0.409767,0.241417,0.630877,0.309971,0.551766,0.560705,0.601212
116926,0.185927,0.705623,0.214580,0.773403,0.208316,0.480058,0.448769,0.240525
116927,0.029084,0.415529,0.200117,0.684262,0.268128,0.443388,0.287822,0.497842
116928,0.080818,0.501545,0.201478,0.501345,0.265744,0.532484,0.459098,0.211959
116929,0.085243,0.512349,0.233872,0.761917,0.319169,0.480732,0.424174,0.225943

##  <h1 style='color:MediumVioletRed' align="center" > DecisionTree Model with PCA </h1>

In [20]:
from sklearn import tree
model = tree.DecisionTreeClassifier()
model.fit(X_train, y_train)
print(f'DecisionTree Model Train accuracy = 
      {model.score(X_train, y_train)}')
print(f'DecisionTree Model Test accuracy = 
      {model.score(X_test, y_test)}')

DecisionTree Model Train accuracy = 0.9958265361318918
DecisionTree Model Test accuracy = 0.9548276746771572

##  <h1 style='color:MediumVioletRed' align="center" > RandomForest Model with PCA </h1>

In [21]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(n_estimators=8)
model.fit(X_train, y_train)

print(f'RandomForest Model Train accuracy = 
      {model.score(X_train, y_train)}')

print(f'RandomForest Model Test accuracy = 
      {model.score(X_test, y_test)}')

RandomForest Model Train accuracy = 0.9949905605312614
RandomForest Model Test accuracy = 0.9717865389549303

## <h1 style='color:MediumVioletRed' align="center" > GBC Model with PCA </h1>

In [20]:
from sklearn.ensemble import GradientBoostingClassifier

GBCModel = GradientBoostingClassifier(n_estimators=300, 
      max_depth=15, learning_rate=0.9, random_state=44)
GBCModel.fit(X_train, y_train)

print('GBCModel Train Score is : ' ,
      GBCModel.score(X_train, y_train))

print('GBCModel Test Score is : ' , 
      GBCModel.score(X_test, y_test))

GBCModel Train Score is :  0.9955635565951205
GBCModel Test Score is :  0.963892927392457

In [ ]:
X = ourdata_upsampled.drop(columns='HeartDisease')
y = ourdata_upsampled['HeartDisease']

ourdata_upsampled

import pandas as pd
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler


pca = PCA()
pca.fit(X)

# calculate the percentage of variance explained by each component
variance = pca.explained_variance_ratio_
variance_ratio = pd.DataFrame(variance, columns=['Explained Variance'])
variance_ratio['Cumulative Variance'] = variance_ratio['Explained Variance'].cumsum()
print(variance_ratio)

components = pd.DataFrame(pca.components_, columns=X.columns)
important_features = components.iloc[0]




X.shape



from sklearn.decomposition import PCA
import numpy as np
pca = PCA(n_components=8)
pca.fit(X)
X_reduced = pca.transform(X)
print("Original data:\n", X)
print("Reduced data:\n", X_reduced)

X_reduced.shape

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X_reduced, y, test_size = 0.2, random_state = 15)

X_train.shape

X_test.shape

from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

X_train = scaler.fit_transform(X_train)

X_test = scaler.transform(X_test)
X_train = pd.DataFrame(X_train)
X_test = pd.DataFrame(X_test)

X_train

X_test



##  <h1 style='color:MediumVioletRed' align="center" > DecisionTree Model with PCA </h1>

from sklearn import tree
model = tree.DecisionTreeClassifier()
model.fit(X_train, y_train)
print(f'DecisionTree Model Train accuracy = 
      {model.score(X_train, y_train)}')
print(f'DecisionTree Model Test accuracy = 
      {model.score(X_test, y_test)}') 

##  <h1 style='color:MediumVioletRed' align="center" > RandomForest Model with PCA </h1>


from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(n_estimators=8)
model.fit(X_train, y_train)

print(f'RandomForest Model Train accuracy = 
      {model.score(X_train, y_train)}')

print(f'RandomForest Model Test accuracy = 
      {model.score(X_test, y_test)}')

## <h1 style='color:MediumVioletRed' align="center" > GBC Model with PCA </h1>


from sklearn.ensemble import GradientBoostingClassifier

GBCModel = GradientBoostingClassifier(n_estimators=300, 
      max_depth=15, learning_rate=0.9, random_state=44)
GBCModel.fit(X_train, y_train)

print('GBCModel Train Score is : ' ,
      GBCModel.score(X_train, y_train))

print('GBCModel Test Score is : ' , 
      GBCModel.score(X_test, y_test))