#  **<h1 style='color:Indigo' align="center" > libraries </h1>**

In [52]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline 
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.utils import resample

In [53]:
ourdata= pd.read_csv('D:\\dr_ds.csv') 
ourdata.shape 
#1500   dr_ds5000row..

(319795, 18)

In [54]:
ourdata

,HeartDisease,BMI,Smoking,AlcoholDrinking,Stroke,PhysicalHealth,MentalHealth,DiffWalking,Sex,AgeCategory,Race,Diabetic,PhysicalActivity,GenHealth,SleepTime,Asthma,KidneyDisease,SkinCancer
0,No,16.60,Yes,No,No,3.0,30.0,No,Female,55-59,White,Yes,Yes,Very good,5.0,Yes,No,Yes
1,No,20.34,No,No,Yes,0.0,0.0,No,Female,80 or older,White,No,Yes,Very good,7.0,No,No,No
2,No,26.58,Yes,No,No,20.0,30.0,No,Male,65-69,White,Yes,Yes,Fair,8.0,Yes,No,No
3,No,24.21,No,No,No,0.0,0.0,No,Female,75-79,White,No,No,Good,6.0,No,No,Yes
4,No,23.71,No,No,No,28.0,0.0,Yes,Female,40-44,White,No,Yes,Very good,8.0,No,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
319790,Yes,27.41,Yes,No,No,7.0,0.0,Yes,Male,60-64,Hispanic,Yes,No,Fair,6.0,Yes,No,No
319791,No,29.84,Yes,No,No,0.0,0.0,No,Male,35-39,Hispanic,No,Yes,Very good,5.0,Yes,No,No
319792,No,24.24,No,No,No,0.0,0.0,No,Female,45-49,Hispanic,No,Yes,Good,6.0,No,No,No
319793,No,32.81,No,No,No,0.0,0.0,No,Female,25-29,Hispanic,No,No,Good,12.0,No,No,No
319794,No,46.56,No,No,No,0.0,0.0,No,Female,80 or older,Hispanic,No,Yes,Good,8.0,No,No,No

#  **<h1 style='color:Indigo' align="center" > Data Cleaning </h1>**

In [55]:
duplicates=ourdata.duplicated()
print(sum(duplicates))

18078

In [56]:
ourdata.isna().sum()

HeartDisease        0
BMI                 0
Smoking             0
AlcoholDrinking     0
Stroke              0
PhysicalHealth      0
MentalHealth        0
DiffWalking         0
Sex                 0
AgeCategory         0
Race                0
Diabetic            0
PhysicalActivity    0
GenHealth           0
SleepTime           0
Asthma              0
KidneyDisease       0
SkinCancer          0
dtype: int64

In [57]:
data = ourdata[~ourdata.isin(['?'])] 
data.loc[:100]

,HeartDisease,BMI,Smoking,AlcoholDrinking,Stroke,PhysicalHealth,MentalHealth,DiffWalking,Sex,AgeCategory,Race,Diabetic,PhysicalActivity,GenHealth,SleepTime,Asthma,KidneyDisease,SkinCancer
0,No,16.60,Yes,No,No,3.0,30.0,No,Female,55-59,White,Yes,Yes,Very good,5.0,Yes,No,Yes
1,No,20.34,No,No,Yes,0.0,0.0,No,Female,80 or older,White,No,Yes,Very good,7.0,No,No,No
2,No,26.58,Yes,No,No,20.0,30.0,No,Male,65-69,White,Yes,Yes,Fair,8.0,Yes,No,No
3,No,24.21,No,No,No,0.0,0.0,No,Female,75-79,White,No,No,Good,6.0,No,No,Yes
4,No,23.71,No,No,No,28.0,0.0,Yes,Female,40-44,White,No,Yes,Very good,8.0,No,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96,No,24.02,No,No,No,0.0,14.0,No,Female,70-74,White,No,Yes,Very good,7.0,No,No,Yes
97,No,28.35,Yes,No,No,20.0,0.0,No,Female,65-69,White,No,No,Very good,8.0,No,No,No
98,No,24.37,No,No,No,0.0,0.0,No,Female,55-59,White,No,Yes,Very good,7.0,Yes,No,No
99,No,19.47,Yes,No,No,0.0,10.0,No,Female,65-69,White,No,Yes,Very good,8.0,No,No,No
100,No,24.80,No,No,No,8.0,0.0,No,Female,80 or older,White,"No, borderline diabetes",Yes,Excellent,8.0,No,No,No

#  **<h1 style='color:Indigo' align="center" > Data Processing </h1>**

In [58]:
cols_yes__no_values = ['HeartDisease', 'Smoking', 'AlcoholDrinking', 'Stroke', 'DiffWalking', 'PhysicalActivity',
                       'Asthma', 'KidneyDisease', 'SkinCancer']
yes__no_values = {'No':0, 'Yes':1}
for i in range(0, len(cols_yes__no_values)):
    ourdata[cols_yes__no_values[i]] = ourdata[cols_yes__no_values[i]].replace(yes__no_values)
sex = {'Female':0, 'Male':1}
ourdata['Sex'] = ourdata['Sex'].replace(sex)

ageCategory= {'18-24':0, '25-29':1, '30-34':2, '35-39':3, '40-44':4, '45-49':5, '50-54':6, '55-59':7, '60-64':8,
             '65-69':9, '70-74':10, '75-79':11, '80 or older':12}
ourdata['AgeCategory'] = ourdata['AgeCategory'].replace(ageCategory)
genHealth = {'Poor':0, 'Fair':1, 'Good':2, 'Very good':3, 'Excellent':4}
ourdata['GenHealth'] = ourdata['GenHealth'].replace(genHealth)
diabetic = {'No':0, 'No, borderline diabetes':1, 'Yes (during pregnancy)':2, 'Yes':3}
ourdata['Diabetic'] = ourdata['Diabetic'].replace(diabetic)
ourdata.drop(columns=['Race'], inplace=True)
ourdata

,HeartDisease,BMI,Smoking,AlcoholDrinking,Stroke,PhysicalHealth,MentalHealth,DiffWalking,Sex,AgeCategory,Diabetic,PhysicalActivity,GenHealth,SleepTime,Asthma,KidneyDisease,SkinCancer
0,0,16.60,1,0,0,3.0,30.0,0,0,7,3,1,3,5.0,1,0,1
1,0,20.34,0,0,1,0.0,0.0,0,0,12,0,1,3,7.0,0,0,0
2,0,26.58,1,0,0,20.0,30.0,0,1,9,3,1,1,8.0,1,0,0
3,0,24.21,0,0,0,0.0,0.0,0,0,11,0,0,2,6.0,0,0,1
4,0,23.71,0,0,0,28.0,0.0,1,0,4,0,1,3,8.0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
319790,1,27.41,1,0,0,7.0,0.0,1,1,8,3,0,1,6.0,1,0,0
319791,0,29.84,1,0,0,0.0,0.0,0,1,3,0,1,3,5.0,1,0,0
319792,0,24.24,0,0,0,0.0,0.0,0,0,5,0,1,2,6.0,0,0,0
319793,0,32.81,0,0,0,0.0,0.0,0,0,1,0,0,2,12.0,0,0,0
319794,0,46.56,0,0,0,0.0,0.0,0,0,12,0,1,2,8.0,0,0,0

In [59]:
ourdata_majority_0 = ourdata[(ourdata['HeartDisease']==0)] 
ourdata_minority_1 = ourdata[(ourdata['HeartDisease']==1)] 

ourdata_minority_upsampled = resample(ourdata_minority_1, 
                                 replace=True,    
                                 n_samples= 292225, #292225
                                 random_state=42) 

ourdata_upsampled = pd.concat([ourdata_minority_upsampled, ourdata_majority_0])

In [60]:
ourdata_upsampled

,HeartDisease,BMI,Smoking,AlcoholDrinking,Stroke,PhysicalHealth,MentalHealth,DiffWalking,Sex,AgeCategory,Diabetic,PhysicalActivity,GenHealth,SleepTime,Asthma,KidneyDisease,SkinCancer
276535,1,35.43,0,1,1,0.0,0.0,1,0,12,0,0,2,12.0,0,0,0
183941,1,23.06,0,0,0,0.0,0.0,0,1,12,3,1,1,8.0,0,0,0
8829,1,23.49,1,0,0,5.0,0.0,0,1,12,3,1,1,7.0,0,0,0
60254,1,26.63,1,0,0,4.0,3.0,1,0,12,3,1,1,10.0,0,0,0
251583,1,28.07,0,1,0,0.0,0.0,0,1,11,0,1,4,8.0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
319789,0,22.22,0,0,0,0.0,0.0,0,0,0,0,1,4,8.0,0,0,0
319791,0,29.84,1,0,0,0.0,0.0,0,1,3,0,1,3,5.0,1,0,0
319792,0,24.24,0,0,0,0.0,0.0,0,0,5,0,1,2,6.0,0,0,0
319793,0,32.81,0,0,0,0.0,0.0,0,0,1,0,0,2,12.0,0,0,0
319794,0,46.56,0,0,0,0.0,0.0,0,0,12,0,1,2,8.0,0,0,0

#  **<h1 style='color:Indigo' align="center" > Data Spliting </h1>**

In [61]:
X = ourdata_upsampled.drop(columns='HeartDisease')
y = ourdata_upsampled['HeartDisease']

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 15)

#  **<h1 style='color:Indigo' align="center" > Data Scaling </h1>**

In [62]:

from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)
X_train = pd.DataFrame(X_train)
X_test = pd.DataFrame(X_test)

In [63]:
X_train.shape

(467717, 16)

In [64]:
X_test

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,0.138196,0.0,0.0,0.0,0.000000,0.000000,0.0,1.0,0.000000,0.000000,1.0,1.00,0.347826,0.0,0.0,0.0
1,0.178519,0.0,0.0,0.0,0.000000,0.033333,0.0,0.0,1.000000,0.000000,0.0,0.75,0.304348,1.0,0.0,0.0
2,0.164712,0.0,0.0,0.0,0.066667,0.400000,1.0,0.0,0.833333,1.000000,1.0,0.25,0.217391,0.0,1.0,1.0
3,0.148094,1.0,0.0,0.0,0.100000,1.000000,1.0,0.0,0.666667,0.333333,0.0,0.25,0.304348,0.0,0.0,0.0
4,0.153837,1.0,0.0,0.0,1.000000,0.033333,1.0,0.0,1.000000,0.000000,0.0,0.00,0.217391,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
116925,0.193915,0.0,0.0,0.0,0.000000,0.000000,0.0,1.0,0.333333,0.000000,1.0,1.00,0.304348,0.0,0.0,1.0
116926,0.168622,0.0,0.0,0.0,0.000000,0.500000,0.0,0.0,0.000000,0.000000,1.0,0.75,0.173913,0.0,0.0,0.0
116927,0.150415,0.0,0.0,0.0,0.000000,0.000000,0.0,1.0,0.250000,0.000000,0.0,0.50,0.260870,0.0,0.0,0.0
116928,0.154814,0.0,0.0,0.0,0.000000,0.166667,0.0,0.0,0.500000,0.000000,1.0,0.75,0.260870,0.0,0.0,0.0
116929,0.186217,0.0,0.0,0.0,0.000000,0.166667,0.0,0.0,0.083333,0.000000,1.0,0.75,0.304348,0.0,0.0,0.0

#  **<h1 style='color:Indigo' align="center" > RF</h1>**

##  <h1 style='color:MediumVioletRed' align="center" > RandomForest Model</h1>

**<span style = 'color : green '><font size ='5'> RandomForest </font></span>**
**<span style = 'color : black '><font size ='4'>model with </font></span>**
**<span style = 'color : blue '><font size ='5'> 100 </font></span>**
**<span style = 'color : black '><font size ='4'> DecisionTree </font></span>**
**<span style = 'color : black '><font size ='4'> accuracy =  </font></span>**
**<span style = 'color : red '><font size ='6'>  96,70 % </font></span>**

In [16]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(n_estimators=100)
model.fit(X_train, y_train)

print(f'RandomForest Model Train accuracy = {model.score(X_train, y_train)}')

print(f'RandomForest Model Test accuracy = {model.score(X_test, y_test)}')

RandomForest Model Train accuracy = 0.9958243980868773
RandomForest Model Test accuracy = 0.9669716924655777

**<span style = 'color : green '><font size ='5'> RandomForest </font></span>**
**<span style = 'color : black '><font size ='4'>model with </font></span>**
**<span style = 'color : blue '><font size ='5'> 50 </font></span>**
**<span style = 'color : black '><font size ='4'> DecisionTree </font></span>**
**<span style = 'color : black '><font size ='4'> accuracy =  </font></span>**
**<span style = 'color : red '><font size ='6'>  96,70 % </font></span>**

In [17]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(n_estimators=50)
model.fit(X_train, y_train)

print(f'RandomForest Model Train accuracy = {model.score(X_train, y_train)}')

print(f'RandomForest Model Test accuracy = {model.score(X_test, y_test)}')

RandomForest Model Train accuracy = 0.9957688089165029
RandomForest Model Test accuracy = 0.9670914222184213


**<span style = 'color : green '><font size ='5'> RandomForest </font></span>**
**<span style = 'color : black '><font size ='4'>model with </font></span>**
**<span style = 'color : blue '><font size ='5'> 10 </font></span>**
**<span style = 'color : black '><font size ='4'> DecisionTree </font></span>**
**<span style = 'color : black '><font size ='4'> accuracy =  </font></span>**
**<span style = 'color : red '><font size ='6'>  96,8 % </font></span>**

In [18]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(n_estimators=10)
model.fit(X_train, y_train)

print(f'RandomForest Model Train accuracy = {model.score(X_train, y_train)}')

print(f'RandomForest Model Test accuracy = {model.score(X_test, y_test)}')

RandomForest Model Train accuracy = 0.9949071767756998
RandomForest Model Test accuracy = 0.9677841443598735


**<span style = 'color : green '><font size ='5'> RandomForest </font></span>**
**<span style = 'color : black '><font size ='4'>model with </font></span>**
**<span style = 'color : blue '><font size ='5'> 5 </font></span>**
**<span style = 'color : black '><font size ='4'> DecisionTree </font></span>**
**<span style = 'color : black '><font size ='4'> accuracy =  </font></span>**
**<span style = 'color : red '><font size ='6'>  95,7 % </font></span>**

In [19]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(n_estimators=5)
model.fit(X_train, y_train)

print(f'RandomForest Model Train accuracy = {model.score(X_train, y_train)}')

print(f'RandomForest Model Test accuracy = {model.score(X_test, y_test)}')

RandomForest Model Train accuracy = 0.9912703622062059
RandomForest Model Test accuracy = 0.9571281963567947


**<span style = 'color : green '><font size ='5'> RandomForest </font></span>**
**<span style = 'color : black '><font size ='4'>model with </font></span>**
**<span style = 'color : blue '><font size ='5'> 8 </font></span>**
**<span style = 'color : black '><font size ='4'> DecisionTree </font></span>**
**<span style = 'color : black '><font size ='4'> accuracy =  </font></span>**
**<span style = 'color : red '><font size ='6'>  96,8 % </font></span>**

In [20]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(n_estimators=8)
model.fit(X_train, y_train)

print(f'RandomForest Model Train accuracy = {model.score(X_train, y_train)}')

print(f'RandomForest Model Test accuracy = {model.score(X_test, y_test)}')

RandomForest Model Train accuracy = 0.9945437091232519
RandomForest Model Test accuracy = 0.967749935859061